on: [workflow_dispatch]

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build image
        run: docker build . -t danielhuglen/adventurers-guild:latest
      - name: Push image to docker hub
        run: |
          docker login -u danielhuglen -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push danielhuglen/adventurers-guild:latest
